// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthenticateData, AuthenticateResponses, CreateYocoOrderData, CreateYocoOrderResponses, GetAllergensData, GetAllergensResponses, GetAllRestaurantsData, GetAllRestaurantsResponses, GetAppVersionData, GetAppVersionResponses, GetClientData, GetClientResponses, GetDefaultMenuData, GetDefaultMenuIdData, GetDefaultMenuIdResponses, GetDefaultMenuResponses, GetDeliveryRangeTypeData, GetDeliveryRangeTypeResponses, GetFrontEndAppConfigData, GetFrontEndAppConfigResponses, GetGiftCardsData, GetGiftCardsResponses, GetMenuForLocationData, GetMenuForLocationResponses, GetMenusForLocationData, GetMenusForLocationResponses, GetNewsData, GetNewsResponses, GetOrderHistoryData, GetOrderHistoryResponses, GetProfileData, GetProfileResponses, GetPublicStripeKeyData, GetPublicStripeKeyResponses, GetSnoozeDataData, GetSnoozeDataResponses, GetVouchersData, GetVouchersResponses, ListPaymentCardsData, ListPaymentCardsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get frontend application configuration
 *
 * Returns app-wide config including allowed card networks, country codes, bill pay options, and feature flags.
 */
export const getFrontEndAppConfig = <ThrowOnError extends boolean = false>(options?: Options<GetFrontEndAppConfigData, ThrowOnError>) => (options?.client ?? client).get<GetFrontEndAppConfigResponses, unknown, ThrowOnError>({ url: '/front_end_app_config', ...options });

/**
 * Get client (brand) information
 *
 * Returns brand name, logos, description, and hero images.
 */
export const getClient = <ThrowOnError extends boolean = false>(options?: Options<GetClientData, ThrowOnError>) => (options?.client ?? client).get<GetClientResponses, unknown, ThrowOnError>({ url: '/client', ...options });

/**
 * Get public Stripe key
 */
export const getPublicStripeKey = <ThrowOnError extends boolean = false>(options?: Options<GetPublicStripeKeyData, ThrowOnError>) => (options?.client ?? client).get<GetPublicStripeKeyResponses, unknown, ThrowOnError>({ url: '/public_stripe_key', ...options });

/**
 * Get minimum app version
 */
export const getAppVersion = <ThrowOnError extends boolean = false>(options?: Options<GetAppVersionData, ThrowOnError>) => (options?.client ?? client).get<GetAppVersionResponses, unknown, ThrowOnError>({ url: '/appversion', ...options });

/**
 * Get delivery range type
 *
 * Returns how delivery zones are defined (e.g. polygon, radius).
 */
export const getDeliveryRangeType = <ThrowOnError extends boolean = false>(options?: Options<GetDeliveryRangeTypeData, ThrowOnError>) => (options?.client ?? client).get<GetDeliveryRangeTypeResponses, unknown, ThrowOnError>({ url: '/get_delivery_range_type', ...options });

/**
 * Get default menu ID
 */
export const getDefaultMenuId = <ThrowOnError extends boolean = false>(options?: Options<GetDefaultMenuIdData, ThrowOnError>) => (options?.client ?? client).get<GetDefaultMenuIdResponses, unknown, ThrowOnError>({ url: '/get_default_menu_id', ...options });

/**
 * Get full default menu with all items and deal groups
 *
 * Returns the complete menu structure with entry groups, items, deal configurations, pricing, images, allergens, and availability windows.
 */
export const getDefaultMenu = <ThrowOnError extends boolean = false>(options: Options<GetDefaultMenuData, ThrowOnError>) => (options.client ?? client).get<GetDefaultMenuResponses, unknown, ThrowOnError>({ url: '/get_default_menu/{menuId}', ...options });

/**
 * Get menu snooze and availability data
 *
 * Returns per-location data on snoozed/disabled SKUs, order acceptance status, collection/delivery enablement, time slots, and kitchen configuration.
 */
export const getSnoozeData = <ThrowOnError extends boolean = false>(options?: Options<GetSnoozeDataData, ThrowOnError>) => (options?.client ?? client).get<GetSnoozeDataResponses, unknown, ThrowOnError>({ url: '/ikentoo_menu/get_snooze_data', ...options });

/**
 * Get all restaurant locations
 *
 * Returns all restaurant locations with addresses, coordinates, opening times, order capabilities, delivery zones, and kitchen status.
 */
export const getAllRestaurants = <ThrowOnError extends boolean = false>(options?: Options<GetAllRestaurantsData, ThrowOnError>) => (options?.client ?? client).get<GetAllRestaurantsResponses, unknown, ThrowOnError>({ url: '/restaurants/all', ...options });

/**
 * Get allergen list
 *
 * Returns all available allergen codes with localized labels.
 */
export const getAllergens = <ThrowOnError extends boolean = false>(options?: Options<GetAllergensData, ThrowOnError>) => (options?.client ?? client).get<GetAllergensResponses, unknown, ThrowOnError>({ url: '/allergens', ...options });

/**
 * Get available menus for a location
 *
 * Returns list of menu names/IDs available at a specific business location.
 */
export const getMenusForLocation = <ThrowOnError extends boolean = false>(options: Options<GetMenusForLocationData, ThrowOnError>) => (options.client ?? client).get<GetMenusForLocationResponses, unknown, ThrowOnError>({ url: '/ikentoo_menus/location/{locationId}', ...options });

/**
 * Get full menu for a specific location
 *
 * Returns the complete menu for a location including location-specific channel link ID and availability. Same structure as default menu but scoped to a location.
 */
export const getMenuForLocation = <ThrowOnError extends boolean = false>(options: Options<GetMenuForLocationData, ThrowOnError>) => (options.client ?? client).get<GetMenuForLocationResponses, unknown, ThrowOnError>({ url: '/ikentoo_menu/{menuId}/location/{locationId}', ...options });

/**
 * Authenticate via social login
 *
 * Authenticates a user via Apple or Google social login. Returns a JWT token and user profile on success,
 * or a `try_register` flag if the account doesn't exist yet.
 *
 */
export const authenticate = <ThrowOnError extends boolean = false>(options: Options<AuthenticateData, ThrowOnError>) => (options.client ?? client).post<AuthenticateResponses, unknown, ThrowOnError>({
    url: '/api-token-auth',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user profile
 *
 * Returns the authenticated user's full profile including loyalty balance, stamp cards, addresses, and subscription status.
 */
export const getProfile = <ThrowOnError extends boolean = false>(options?: Options<GetProfileData, ThrowOnError>) => (options?.client ?? client).get<GetProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me',
    ...options
});

/**
 * Get user order history
 *
 * Returns paginated list of past orders with full item details.
 */
export const getOrderHistory = <ThrowOnError extends boolean = false>(options: Options<GetOrderHistoryData, ThrowOnError>) => (options.client ?? client).get<GetOrderHistoryResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/orders/{page}',
    ...options
});

/**
 * Get user vouchers
 *
 * Returns available and redeemed vouchers/rewards for the user.
 */
export const getVouchers = <ThrowOnError extends boolean = false>(options?: Options<GetVouchersData, ThrowOnError>) => (options?.client ?? client).get<GetVouchersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/vouchers',
    ...options
});

/**
 * Get user gift cards
 *
 * Returns the user's gift card balances and profile info.
 */
export const getGiftCards = <ThrowOnError extends boolean = false>(options?: Options<GetGiftCardsData, ThrowOnError>) => (options?.client ?? client).get<GetGiftCardsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/gift_cards',
    ...options
});

/**
 * Get news feed
 */
export const getNews = <ThrowOnError extends boolean = false>(options?: Options<GetNewsData, ThrowOnError>) => (options?.client ?? client).get<GetNewsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/news',
    ...options
});

/**
 * List saved payment cards
 *
 * Returns saved payment cards for the authenticated user.
 */
export const listPaymentCards = <ThrowOnError extends boolean = false>(options: Options<ListPaymentCardsData, ThrowOnError>) => (options.client ?? client).post<ListPaymentCardsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orders/list_payment_cards',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create an order with Yoco payment
 *
 * Submits a complete order with items, customizations, delivery/collection details, and
 * payment info. Returns the created order and a Yoco checkout object with a redirect URL
 * for the customer to complete payment.
 *
 */
export const createYocoOrder = <ThrowOnError extends boolean = false>(options: Options<CreateYocoOrderData, ThrowOnError>) => (options.client ?? client).post<CreateYocoOrderResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/order/create_yoco_order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
