// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://hybrid-deliverect-lightspeed.5loyalty.com' | (string & {});
};

export type ApiResponse = {
    message?: string;
    status?: number;
};

export type ClientInfo = {
    name?: string;
    favicon_image?: string;
    logo_image?: string;
    logo_image_light?: string;
    test_user_id?: string | null;
    buisiness_description?: string;
    gift_voucher_description?: string;
    buisiness_name?: string;
    hero_image?: string;
    main_image?: string;
};

export type Menu = {
    menuName?: string;
    menu_id?: string;
    ikentooMenuId?: string;
    /**
     * Deliverect channel link ID
     */
    channelLinkId?: string;
    deliverect_availability?: Array<{
        dayOfWeek?: number;
        startTime?: string;
        endTime?: string;
    }>;
    menuEntryGroups?: Array<MenuEntryGroup>;
};

export type MenuEntryGroup = {
    '@type'?: 'group';
    name?: string;
    color?: string;
    menuEntry?: Array<MenuItem>;
};

/**
 * A menu item or deal. Deals contain `menuDealGroups` for customization.
 */
export type MenuItem = {
    '@type'?: 'menuItem' | 'menuDeal';
    productName?: string;
    description?: string;
    color?: string;
    /**
     * Price as string in ZAR
     */
    productPrice?: string;
    sku?: string;
    productionInstructionList?: Array<string>;
    type?: 'menuItem' | 'menuDeal';
    itemRichData?: ItemRichData;
    /**
     * Tax rate in millipercent (15000 = 15%)
     */
    deliveryTax?: number;
    takeawayTax?: number;
    eatInTax?: number;
    taxIncludedInPrice?: boolean;
    defaultTaxPercentage?: string;
    defaultTaxAmount?: string;
    /**
     * Only present for menuDeal type items
     */
    menuDealGroups?: Array<MenuDealGroup>;
};

export type ItemRichData = {
    squareImageUrl?: string | null;
    rawImageUrl?: string | null;
    texts?: Array<{
        locale?: string;
        friendlyDisplayName?: string;
        description?: string;
    }>;
    allergenCodes?: Array<string>;
};

/**
 * A customization group within a deal (e.g. "Choose Your Base", "Pick a Protein")
 */
export type MenuDealGroup = {
    description?: string;
    mustSelectAnItem?: boolean;
    multiSelectionPermitted?: boolean;
    isUpsell?: boolean;
    /**
     * Maximum selections allowed
     */
    max?: number;
    /**
     * Minimum selections required
     */
    min?: number;
    items?: Array<MenuItem>;
};

export type SnoozeData = {
    business_location_id?: string;
    data?: {
        is_accepting_orders_currently?: boolean;
        delivery_enabled?: boolean;
        collection_enabled?: boolean;
        table_enabled?: boolean;
        pick_up_at_counter_enabled?: boolean;
        browse_menu_enabled?: boolean;
        snoozed_skus?: Array<string>;
        disabled_skus?: Array<string>;
        snoozed_times?: {
            'charter-delivery'?: Array<string>;
            collection?: Array<string>;
        };
        disabled_times?: {
            'charter-delivery'?: Array<string>;
            collection?: Array<string>;
        };
        /**
         * Estimated collection time in minutes
         */
        collection_time?: number;
        delivery_time?: number;
        print_time_collection?: number;
        print_time_delivery?: number;
        interval_time?: number;
        interval_time_delivery?: number;
        can_scheduled_collection_order?: boolean;
        can_scheduled_delivery_order?: boolean;
        /**
         * JSON string of per-channel order limits
         */
        autosnooze_limit?: string;
        timeslot_order_count?: {
            [key: string]: unknown;
        };
        timeslot_delivery_order_count?: {
            [key: string]: unknown;
        };
        open_close_times?: {
            collection_open?: string;
            collection_close?: string;
            delivery_open?: string;
            delivery_close?: string;
        };
    };
};

export type Restaurant = {
    id?: number;
    name?: string;
    description?: string;
    address?: string;
    town?: string;
    county?: string;
    postcode?: string;
    email?: string;
    order_confirmation_email_json?: string;
    telephone?: string;
    website?: string;
    facebook?: string;
    twitter?: string;
    /**
     * Comma-separated lat,lng
     */
    position?: string;
    opening_times?: string;
    business_location_id?: string;
    menu_id?: string;
    unavailable_slots?: Array<string>;
    available_tables?: Array<{
        [key: string]: unknown;
    }>;
    json_opening_times?: Array<{
        [key: string]: unknown;
    }>;
    json_time_selector?: Array<{
        [key: string]: unknown;
    }>;
    show_discount?: boolean;
    image?: string | null;
    coming_soon?: boolean;
    can_table_order?: boolean;
    can_delivery_order?: boolean;
    can_charter_delivery_order?: boolean;
    can_collection_order?: boolean;
    can_scheduled_collection_order?: boolean;
    can_scheduled_delivery_order?: boolean;
    can_pick_up_at_counter?: boolean;
    is_pickup?: boolean;
    is_accepting_orders_currently?: boolean;
    snoozed_skus?: Array<string>;
    disabled_skus?: Array<string>;
    delivery_zone_config?: Array<{
        [key: string]: unknown;
    }>;
    pickup_points?: Array<{
        [key: string]: unknown;
    }>;
    kitchen_status?: {
        text?: string;
        status?: number;
    };
    is_published?: boolean;
};

export type Allergen = {
    code?: string;
    translations?: Array<{
        locale?: string;
        text?: string;
    }>;
};

export type AuthRequest = {
    /**
     * Empty string for social auth
     */
    username: string;
    socialAuth: {
        /**
         * JWT identity token from the social provider
         */
        tokenId: string;
        /**
         * Authorization code (Apple only)
         */
        code?: string;
        authType: 'Apple' | 'Google';
    };
    client_id?: number | null;
    version?: string;
};

export type AuthSuccessResponse = {
    /**
     * JWT access token for authenticated requests
     */
    token?: string;
    profile?: UserProfile;
};

export type AuthRegisterResponse = {
    try_register?: boolean;
    message?: string;
};

export type UserProfile = {
    id?: string;
    client?: number;
    user_token?: string;
    email?: string;
    mobile?: string;
    mobile_code?: string;
    mobile_value?: string;
    first_name?: string;
    last_name?: string;
    birthday?: string | null;
    qr_code?: string;
    /**
     * Loyalty points available
     */
    available_balance?: number;
    milestone_balance?: number;
    total_earned_to_date?: number;
    card_last_four?: string | null;
    card_expiry?: string | null;
    card_type?: string | null;
    promotion_consent?: boolean;
    profile_image_url?: string | null;
    is_subscribed?: boolean;
    accepted_terms_and_conditions?: boolean;
    locale?: string;
    email_verified?: string;
    is_verification_pop_up_shown?: boolean;
    judo_pay_cards?: Array<{
        [key: string]: unknown;
    }>;
    address_list?: Array<{
        [key: string]: unknown;
    }>;
    charter_delivery_address_list?: Array<{
        [key: string]: unknown;
    }>;
    pickup_points_list?: Array<{
        [key: string]: unknown;
    }>;
    scan_is_payment?: boolean;
    scan_is_loyalty?: boolean;
    is_guest?: boolean;
    active_subscription?: {
        [key: string]: unknown;
    };
    stamp_cards_json?: Array<{
        id?: number;
        stamp_balance?: number;
    }>;
    created_at?: string;
    gender?: string | null;
    dietary_requirements?: string;
    dietary_requirements_list?: Array<string>;
    is_verified?: boolean;
    group_tags?: Array<string>;
};

export type Voucher = {
    id?: number;
    reward?: {
        id?: number;
        name?: string;
        discount_id?: string;
        description?: string;
        show_in_app?: boolean;
        small_print?: string;
        expiry_date?: string;
        /**
         * Cost in loyalty points
         */
        cost?: number;
        is_manual_discount_json?: boolean;
        discount_json?: {
            reward_type?: number;
        };
        image?: string;
        group?: string;
        is_multi_use?: boolean;
    };
    is_locked?: boolean;
    unlock_time?: string;
    reason?: string;
    is_expired?: boolean;
    redeemed?: boolean;
    user?: {
        id?: number;
        email?: string;
    };
    expiry_date?: string;
    voucher_type?: 'voucher';
    is_unlock_reward?: boolean;
    is_milestone?: boolean;
    additional_config?: {
        [key: string]: unknown;
    };
};

export type CreateYocoOrderRequest = {
    /**
     * Cart items, each wrapping a MenuItem/MenuDeal with full customization data
     */
    items: Array<{
        item?: MenuItem;
        quantity?: number;
        special_instructions?: string;
    }>;
    applicable_vouchers?: Array<{
        [key: string]: unknown;
    }>;
    applied_gift_cards?: Array<{
        [key: string]: unknown;
    }>;
    payment_token: string;
    pay_on_collection?: boolean;
    discount_applied?: number;
    business_location_id: string;
    /**
     * 'asap' or ISO datetime
     */
    collection_time?: string;
    mobile: string;
    mobile_code?: string;
    mobile_value?: string;
    currency: string;
    order_type: 'collection' | 'delivery' | 'table';
    delivery_option?: {
        description?: string;
        id?: string;
        isDisabled?: boolean;
        isRemoved?: boolean;
        isHiddenFromSidebar?: boolean;
        label?: string;
        route?: string;
    };
    delivery_address?: {
        [key: string]: unknown;
    } | null;
    pick_up_point?: {
        [key: string]: unknown;
    } | null;
    is_gift?: boolean;
    is_postal_gift?: boolean;
    delivery_price?: number;
    /**
     * Total in rands (human-readable)
     */
    _total?: number;
    /**
     * Total in cents
     */
    total: number;
    min_order?: string;
    delivery_min_order?: number;
    allergen_data?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Unix timestamp in milliseconds
     */
    cutoffTime?: number;
    table_name?: string | null;
    service_charge_percentage?: number;
    service_charge_value?: number;
    is_asap?: boolean;
    menu_id?: string;
    already_paid?: number;
    uuid?: string;
    custom_field?: {
        field_value?: string;
        field_name?: string;
    };
    additional_data?: {
        tax_breakdown?: Array<{
            [key: string]: unknown;
        }>;
        gift_voucher_data?: {
            [key: string]: unknown;
        };
    };
    version?: string;
    client_id?: number | null;
};

export type Order = {
    id?: number;
    is_parent_order?: boolean;
    collection_code?: string;
    items?: Array<{
        item?: MenuItem;
        quantity?: number;
        special_instructions?: string;
    }>;
    collection_time?: string;
    restaurant_name?: string;
    table_name?: string;
    status?: 'new' | 'accepted' | 'ready' | 'completed' | 'cancelled';
    discount?: number;
    created_at?: string;
    payment_token?: string;
    has_multi_basket?: boolean;
    multi_basket_items?: Array<{
        [key: string]: unknown;
    }>;
    eat_in?: boolean;
    take_away?: boolean;
    delivery?: boolean;
    pick_up_point?: boolean;
    delivery_price?: number;
    delivery_address?: {
        [key: string]: unknown;
    };
    mobile?: string;
    amount_paid?: number;
    process_message?: string | null;
    restaurant_id?: number;
    cutoff_time?: string;
    applied_vouchers?: Array<{
        [key: string]: unknown;
    }>;
    is_asap?: boolean;
    payment_info?: {
        [key: string]: unknown;
    };
    service_charge_percentage?: number;
    service_charge_value?: number;
    subscription_discount?: number;
    subscription_price?: number;
    process_fee_value?: number;
    is_gift?: boolean;
    scheduled_collection?: boolean;
    total_taxes?: number;
    kiosk_take_away?: boolean;
    kiosk_eat_in?: boolean;
    pick_up_at_counter?: boolean;
    show_banner?: boolean;
    scheduled_delivery?: boolean;
    uuid?: string;
    additional_data?: {
        [key: string]: unknown;
    };
    events?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Yoco payment checkout session. Redirect the user to `redirectUrl` to complete payment.
 */
export type YocoCheckout = {
    id?: string;
    /**
     * URL to redirect the user to for payment
     */
    redirectUrl?: string;
    status?: 'created' | 'pending' | 'completed' | 'failed';
    /**
     * Amount in cents
     */
    amount?: number;
    currency?: string;
    paymentId?: string | null;
    successUrl?: string;
    cancelUrl?: string;
    failureUrl?: string;
    metadata?: {
        order_id?: number;
        client_id?: number;
        checkoutId?: string;
        paymentFacilitator?: string;
        domain?: string;
    };
    merchantId?: string;
    totalDiscount?: number | null;
    totalTaxAmount?: number | null;
    subtotalAmount?: number | null;
    lineItems?: Array<{
        [key: string]: unknown;
    }> | null;
    processingMode?: 'live' | 'test';
};

/**
 * Client app version
 */
export type Version = string;

export type GetFrontEndAppConfigData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/front_end_app_config';
};

export type GetFrontEndAppConfigResponses = {
    /**
     * App configuration
     */
    200: ApiResponse & {
        data?: {
            front_end_app_config?: {
                allowedCardNetworks?: Array<string>;
                billPay?: {
                    endpointId?: string;
                    staffId?: string;
                };
                billPayOptions?: {
                    errorMessage?: string;
                    hasSplitByCustomAmount?: boolean;
                    hasSplitByItems?: boolean;
                    hasSplitByTableMembers?: boolean;
                };
                country_code_data?: Array<{
                    text?: string;
                    value?: string;
                }>;
            };
        };
    };
};

export type GetFrontEndAppConfigResponse = GetFrontEndAppConfigResponses[keyof GetFrontEndAppConfigResponses];

export type GetClientData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/client';
};

export type GetClientResponses = {
    /**
     * Client info
     */
    200: ApiResponse & {
        data?: ClientInfo;
    };
};

export type GetClientResponse = GetClientResponses[keyof GetClientResponses];

export type GetPublicStripeKeyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/public_stripe_key';
};

export type GetPublicStripeKeyResponses = {
    /**
     * Stripe public key
     */
    200: ApiResponse & {
        data?: {
            public_stripe_key?: string;
        };
    };
};

export type GetPublicStripeKeyResponse = GetPublicStripeKeyResponses[keyof GetPublicStripeKeyResponses];

export type GetAppVersionData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/appversion';
};

export type GetAppVersionResponses = {
    /**
     * App version
     */
    200: ApiResponse & {
        data?: {
            app_version?: string;
        };
    };
};

export type GetAppVersionResponse = GetAppVersionResponses[keyof GetAppVersionResponses];

export type GetDeliveryRangeTypeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/get_delivery_range_type';
};

export type GetDeliveryRangeTypeResponses = {
    /**
     * Delivery range type
     */
    200: ApiResponse & {
        data?: {
            delivery_range_type?: string;
        };
    };
};

export type GetDeliveryRangeTypeResponse = GetDeliveryRangeTypeResponses[keyof GetDeliveryRangeTypeResponses];

export type GetDefaultMenuIdData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/get_default_menu_id';
};

export type GetDefaultMenuIdResponses = {
    /**
     * Default menu ID
     */
    200: ApiResponse & {
        data?: {
            default_menu_id?: string;
        };
    };
};

export type GetDefaultMenuIdResponse = GetDefaultMenuIdResponses[keyof GetDefaultMenuIdResponses];

export type GetDefaultMenuData = {
    body?: never;
    path: {
        menuId: string;
    };
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/get_default_menu/{menuId}';
};

export type GetDefaultMenuResponses = {
    /**
     * Full menu data
     */
    200: ApiResponse & {
        data?: Menu;
    };
};

export type GetDefaultMenuResponse = GetDefaultMenuResponses[keyof GetDefaultMenuResponses];

export type GetSnoozeDataData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/ikentoo_menu/get_snooze_data';
};

export type GetSnoozeDataResponses = {
    /**
     * Snooze data per location
     */
    200: ApiResponse & {
        data?: Array<SnoozeData>;
    };
};

export type GetSnoozeDataResponse = GetSnoozeDataResponses[keyof GetSnoozeDataResponses];

export type GetAllRestaurantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/restaurants/all';
};

export type GetAllRestaurantsResponses = {
    /**
     * Restaurant list
     */
    200: ApiResponse & {
        data?: Array<Restaurant>;
    };
};

export type GetAllRestaurantsResponse = GetAllRestaurantsResponses[keyof GetAllRestaurantsResponses];

export type GetAllergensData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/allergens';
};

export type GetAllergensResponses = {
    /**
     * Allergens
     */
    200: ApiResponse & {
        data?: Array<Allergen>;
    };
};

export type GetAllergensResponse = GetAllergensResponses[keyof GetAllergensResponses];

export type GetMenusForLocationData = {
    body?: never;
    path: {
        locationId: string;
    };
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/ikentoo_menus/location/{locationId}';
};

export type GetMenusForLocationResponses = {
    /**
     * Menus for location
     */
    200: ApiResponse & {
        data?: Array<{
            menuName?: string;
            ikentooMenuId?: string;
        }>;
    };
};

export type GetMenusForLocationResponse = GetMenusForLocationResponses[keyof GetMenusForLocationResponses];

export type GetMenuForLocationData = {
    body?: never;
    path: {
        menuId: string;
        locationId: string;
    };
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/ikentoo_menu/{menuId}/location/{locationId}';
};

export type GetMenuForLocationResponses = {
    /**
     * Location-specific menu
     */
    200: ApiResponse & {
        data?: Menu;
    };
};

export type GetMenuForLocationResponse = GetMenuForLocationResponses[keyof GetMenuForLocationResponses];

export type AuthenticateData = {
    body: AuthRequest;
    path?: never;
    query?: never;
    url: '/api-token-auth';
};

export type AuthenticateResponses = {
    /**
     * Authentication result — either a token + profile, or a registration prompt
     */
    200: AuthSuccessResponse | AuthRegisterResponse;
};

export type AuthenticateResponse = AuthenticateResponses[keyof AuthenticateResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/me';
};

export type GetProfileResponses = {
    /**
     * User profile
     */
    200: {
        id?: number;
        email?: string;
        profile?: UserProfile;
        active_subscription?: {
            [key: string]: unknown;
        };
    };
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetOrderHistoryData = {
    body?: never;
    path: {
        page: number;
    };
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/me/orders/{page}';
};

export type GetOrderHistoryResponses = {
    /**
     * Order history
     */
    200: Array<Order>;
};

export type GetOrderHistoryResponse = GetOrderHistoryResponses[keyof GetOrderHistoryResponses];

export type GetVouchersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/me/vouchers';
};

export type GetVouchersResponses = {
    /**
     * Voucher list
     */
    200: ApiResponse & {
        data?: Array<Voucher>;
    };
};

export type GetVouchersResponse = GetVouchersResponses[keyof GetVouchersResponses];

export type GetGiftCardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/gift_cards';
};

export type GetGiftCardsResponses = {
    /**
     * Gift cards and profile
     */
    200: {
        id?: number;
        email?: string;
        profile?: UserProfile;
    };
};

export type GetGiftCardsResponse = GetGiftCardsResponses[keyof GetGiftCardsResponses];

export type GetNewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client app version
         */
        version?: string;
    };
    url: '/news';
};

export type GetNewsResponses = {
    /**
     * News items
     */
    200: ApiResponse;
};

export type GetNewsResponse = GetNewsResponses[keyof GetNewsResponses];

export type ListPaymentCardsData = {
    body: {
        client_id?: number | null;
        version?: string;
    };
    path?: never;
    query?: never;
    url: '/orders/list_payment_cards';
};

export type ListPaymentCardsResponses = {
    /**
     * Payment cards
     */
    200: ApiResponse & {
        data?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type ListPaymentCardsResponse = ListPaymentCardsResponses[keyof ListPaymentCardsResponses];

export type CreateYocoOrderData = {
    body: CreateYocoOrderRequest;
    path?: never;
    query?: never;
    url: '/order/create_yoco_order';
};

export type CreateYocoOrderResponses = {
    /**
     * Order created with Yoco checkout
     */
    200: ApiResponse & {
        data?: {
            order?: Order;
            client_secret?: string | null;
            yoco?: YocoCheckout;
        };
    };
};

export type CreateYocoOrderResponse = CreateYocoOrderResponses[keyof CreateYocoOrderResponses];
